CREATE TABLE IF NOT EXISTS hypervisor_type (
  id VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  vcpu_spec VARCHAR(255),
  gpu_spec VARCHAR(255),
  cpu_type VARCHAR(255),
  ram_type VARCHAR(255),
  disk_type VARCHAR(255),
  gpu_type VARCHAR(255),
  gpu_total INT NOT NULL DEFAULT 0,
  vcpu_unit INT NOT NULL DEFAULT 0,
  ram_unit INT NOT NULL DEFAULT 0,
  disk_unit INT NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  privately BOOLEAN NOT NULL DEFAULT FALSE,
  original_hourly_pay_price DECIMAL(19,6),
  original_daily_pay_price DECIMAL(19,6),
  original_weekly_pay_price DECIMAL(19,6),
  original_monthly_pay_price DECIMAL(19,6),
  discount_hourly_pay_price DECIMAL(19,6),
  discount_daily_pay_price DECIMAL(19,6),
  discount_weekly_pay_price DECIMAL(19,6),
  discount_monthly_pay_price DECIMAL(19,6),
  PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS hypervisor_host (
  id VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  hostname VARCHAR(255),
  ip VARCHAR(255),
  os_hypervisor_id VARCHAR(255),
  hypervisor_type VARCHAR(255),
  cpu_type VARCHAR(255),
  ram_type VARCHAR(255),
  disk_type VARCHAR(255),
  gpu_type VARCHAR(255),
  vcpus INT NOT NULL DEFAULT 0,
  ram INT NOT NULL DEFAULT 0,
  disk INT NOT NULL DEFAULT 0,
  gpus INT NOT NULL DEFAULT 0,
  used_vcpus INT NOT NULL DEFAULT 0,
  used_ram INT NOT NULL DEFAULT 0,
  used_disk INT NOT NULL DEFAULT 0,
  used_gpus INT NOT NULL DEFAULT 0,
  status VARCHAR(255),
  state VARCHAR(255),
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  region_id VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  INDEX idx_hypervisor_host_region_name (region_id, name)
) ENGINE=InnoDB;
